# Don't print a new line at the start of the prompt
add_newline = false

# Moves the time to the right of the current line
right_format = """$time"""

# Enabling modules with their defaults
[character]                            
success_symbol = "[==>](bold green)"     
error_symbol = "[==>](bold red) "

[username]
format = "  [$user]($style) in "
show_always = true
disabled = false

[status]
disabled = false
symbol = "✖ "

[time]
disabled = false

[battery]
disabled = true

[memory_usage]
disabled = false
